GitHubCode/CourseTrader Web Application/CourseTrader/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Scheduler/', include('Scheduler.urls')),
    
]

GitHubCode/CourseTrader Web Application/Scheduler/urls.py
from django.urls import path

from . import views
app_name = 'Scheduler'
urlpatterns = [
    path('', views.index, name='index'),
    path('students/', views.students, name='students'),
    path('students/<int:pk>/', views.student, name='student'),
    path("register/", views.register_request, name = "register"),
    path("login/", views.login_request, name = "login"),
    path('addclass/<int:pk>/', views.addClass, name = "addclass"),
    path('addwish/<int:pk>/', views.addWish, name = "addwish"),
    path('pairing/<int:pk>/', views.pairing, name = "pairing"),
    path("logout/", views.logout_request, name= "logout"),
]

GitHubCode/CourseTrader Web Application/Scheduler/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    firstname = models.CharField(max_length=70)
    lastname = models.CharField(max_length=70)
    emailaddress = models.CharField(max_length=140)

    def __str__(self):
        return self.lastname + ", " + self.firstname

class Course(models.Model):
    course_number = models.CharField(max_length=10)
    course_name = models.CharField(max_length=140)
    semester = models.CharField(max_length=25)
    credit_hours = models.IntegerField()
    students = models.ManyToManyField(Student, 
    through='Enrollment', 
    )
    wishes = models.ManyToManyField(Student, related_name="wishes",
    through='WishList', 
    )
    
    def __str__(self):
        return self.course_number

class Enrollment(models.Model):
    student = models.ForeignKey(Student, null=True, on_delete=models.SET_NULL)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    period_time = ArrayField(models.CharField(max_length=200), blank=True, null = True,)

class WishList(models.Model):
    student = models.ForeignKey(Student,null=True, on_delete=models.SET_NULL)
    wish = models.ForeignKey(Course, on_delete=models.CASCADE)
    period_time = ArrayField(models.CharField(max_length=200), blank=True, null = True,)

GitHubCode/CourseTrader Web Application/Scheduler/forms.py
from django import forms
from django.forms import ModelForm, TextInput, EmailInput
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Course, Enrollment, Student, WishList
from django.contrib.postgres.fields import ArrayField


class NewUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ("username", "password1", "password2")

class StudentProfileForm(forms.ModelForm):
	class Meta:
		model = Student
		fields = ('firstname', 'lastname', "emailaddress")

class EnrollmentCreationForm(ModelForm):
	course = forms.ModelChoiceField(queryset=Course.objects.all())
	period_time = ArrayField((forms.CharField(max_length=100, required=False)))
	class Meta:
		model = Enrollment
		fields = [
			"student", "course", "period_time"
		]

	def __init__(self, *args, **kwargs):
		self.request = kwargs.pop("request")
		super(EnrollmentCreationForm, self).__init__(*args, **kwargs)
		self.fields['student'].queryset = Student.objects.filter(pk= self.request.user.pk)
		self.fields['student'].empty_label = None
	
class WishListForm(ModelForm):
	wish = forms.ModelChoiceField(queryset=Course.objects.all())
	period_time = ArrayField((forms.CharField(max_length=100, required=False)))

	class Meta:
		model = WishList
		fields = [
			"student", "wish", "period_time",
		]

	def __init__(self, *args, **kwargs):
		self.request = kwargs.pop("request")
		super(WishListForm, self).__init__(*args, **kwargs)
		self.fields['student'].queryset = Student.objects.filter(pk= self.request.user.pk)
		self.fields['student'].empty_label = None

GitHubCode/CourseTrader Web Application/Scheduler/views.py
from django.forms.fields import NullBooleanField
from django.shortcuts import render, redirect
from .forms import EnrollmentCreationForm, NewUserForm, WishListForm, StudentProfileForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.http import HttpResponse
from .models import Enrollment, Student, Course, WishList
from django.template import context, loader
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect

def index(request):
    return render(request, 'Scheduler/home.html')

def students(request):
    student_list = Student.objects.order_by('pk')
    template = loader.get_template('Scheduler/students.html')
    context = {
        'student_list' : student_list
        
    }
    return render(request, 'Scheduler/students.html', context)

    #return HttpResponse(template.render(context, request))

def student(request, pk):
    s = Student.objects.get(pk=pk)
    course_list = s.enrollment_set.all()
    schedule = []
    for enroll in course_list:
        withperiod = (Course.objects.get(pk = enroll.course_id), enroll.period_time)
        schedule.append(withperiod)
   
    courses = []
    wishlist = s.wishlist_set.all()
    for wish in wishlist:
        withperiod = (Course.objects.get(pk = wish.wish_id), wish.period_time)
        courses.append(withperiod)
    context = {
        'course_list' : schedule,
        'courses' : courses,    
    }
    return render(request, 'Scheduler/student.html', context) 
    
def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		student_form = StudentProfileForm(request.POST)
		if form.is_valid() and student_form.is_valid():
			user = form.save()
			profile = student_form.save(commit=False)
			profile.user = user
			profile.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("Scheduler:students")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm(request.POST)
	student_form = StudentProfileForm(request.POST)
	return render (request=request, template_name="Scheduler/register.html", context={"register_form":form, "student_form":student_form})

def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username} {request.user.pk}.")                
				return redirect("Scheduler:student", pk = request.user.pk)
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="Scheduler/login.html", context={"login_form":form})

def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.") 
	return redirect("Scheduler:index")

def addClass(request, pk):
    enroll_form = EnrollmentCreationForm(request.POST or None, request = request)
    if enroll_form.is_valid():
        enroll_form.save()
        return redirect('Scheduler:student', pk = pk) 
    return render(request=request, template_name="Scheduler/addClass.html", context={"form":enroll_form})


def addWish(request, pk):
    wish_form = WishListForm(request.POST or None, request = request)
    if wish_form.is_valid():
        wish_form.save()
        return redirect('Scheduler:student', pk = pk) 
    return render(request=request, template_name="Scheduler/addWish.html", context={"form":wish_form})


def pairing(request, pk):
    pairing = []
    s = Student.objects.get(pk=pk)
    wishes = []
    wishlist = s.wishlist_set.all()
    
    total = Student.objects.exclude(pk=pk)
    
    for wish in wishlist:
        for student in total:
            e = student.enrollment_set.all()
            for enroll in e:
                if wish.wish_id == enroll.course_id and wish.period_time == enroll.period_time and wish.period_time != None:
                    pair = (Student.objects.get(pk = enroll.student_id), Course.objects.get(pk = enroll.course_id), enroll.period_time)
                    pairing.append(pair)

    context = {
        'pairing' : pairing,    
    }
    return render(request, 'Scheduler/pairing.html', context) 

GitHubCode/CourseTrader Web Application/Scheduler/templates/Scheduler/addClass.html
<!DOCTYPE html>
<head>
<style>
    .navigation {
        overflow: hidden;
        font-family: 'Roboto', sans-serif;
    }
    
    .navigation a {
        float: left;
        color: black;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 14px;
    }
    
    .navigation a:hover {
        background-color: rgb(98, 236, 125);
        color: black;
    }
</style>
</head>
<header>
</header>
<body>
<div class="navigation">
        <a href="{% url 'Scheduler:index'%}">Home</a>
        
        {% if user.id == 1 %}
        <a href="{% url 'Scheduler:students' %}">Student List</a>
        {% endif %}

        {% if user.is_authenticated%}
        <a href="{% url 'Scheduler:student' user.pk%}"> View Schedule</a>
        {% else %}
            <a href="{% url 'Scheduler:login'%}">View Schedule</a>
        {% endif %}

        {% if user.is_authenticated %}
            <a href= "{% url 'Scheduler:logout'%}">Logout</a>
        {% else %}
            <a href="{% url 'Scheduler:login'%}">Login</a>
        {% endif %}  
    </div>

<!--Add Class--> 
<div class="container py-5">
	<h1>Add New Class</h1>
	<form method="POST" id="personForm">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name = "submit" value="Add Class To Schedule">
    </form>
</div>


<body>

GitHubCode/CourseTrader Web Application/Scheduler/templates/Scheduler/addWish.html
<!DOCTYPE html>
<head>
<style>
    .navigation {
        overflow: hidden;
        font-family: 'Roboto', sans-serif;
    }
    
    .navigation a {
        float: left;
        color: black;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 14px;
    }
    
    .navigation a:hover {
        background-color: rgb(98, 236, 125);
        color: black;
    }
</style>
</head>
<header>
</header>
<body>
<div class="navigation">
        <a href="{% url 'Scheduler:index'%}">Home</a>
        
        {% if user.id == 1 %}
        <a href="{% url 'Scheduler:students' %}">Student List</a>
        {% endif %}

        {% if user.is_authenticated%}
        <a href="{% url 'Scheduler:student' user.pk%}"> View Schedule</a>
        {% else %}
            <a href="{% url 'Scheduler:login'%}">View Schedule</a>
        {% endif %}

        {% if user.is_authenticated %}
            <a href= "{% url 'Scheduler:logout'%}">Logout</a>
        {% else %}
            <a href="{% url 'Scheduler:login'%}">Login</a>
        {% endif %}  
    </div>

<!--Add Class--> 
<div class="container py-5">
	<h1>Add To Wishlist</h1>
	<form method="POST" id="personForm">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name = "submit" value="Add Class To WishList">
    </form>
</div>


<body>

GitHubCode/CourseTrader Web Application/Scheduler/templates/Scheduler/home.html
<!DOCTYPE html>
<script>
    parent.document.getElementsByTagName('iframe')[0].scrolling = "no";
</script>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@900&display=swap" rel="stylesheet">
    <title>Home</title>

    <style>
    .navigation {
        overflow: hidden;
        font-family: 'Roboto', sans-serif;
    }
    
    .navigation a {
        float: left;
        color: black;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 14px;
    }
    
    .navigation a:hover {
        background-color: rgb(98, 236, 125);
        color: black;
    }
    
    .grid {
        display: grid;
        grid-template-columns: 50% 50%;
        background-color: rgb(98, 236, 125);
        height: 80%;
        width: 100%;
    }
    
    .grid h1 {
        font-family: "Roboto";
        padding-left: 5%;
        padding-bottom: 150px;
    }
    
    .grid p {
        font-family: "Roboto";
        font-size: 18px;
        padding-right: 5%;
    }

    .grid2 {
        display: grid;
        grid-template-columns: 50% 50%;
        
        height: 80%;
        width: 100%;
    }
    
    .grid2 h1 {
        font-family: "Roboto";
        padding-left: 5%;
        padding-bottom: 150px;
    }
    
    .grid2 p {
        font-family: "Roboto";
        font-size: 18px;
        padding-right: 5%;
    }
    
    .grid1 {
        padding-top: 60px;
        display: grid;
        grid-template-columns: 40% 60%;
        height: 60%;
    }
    
    .grid1 h1 {
        font-family: "Roboto";
        padding-left: 5%;
        font-size: 50px;
    }
    
    .grid1 img {
        width: 100%;
        /* height: auto; */
        height: 200px;
        width: 600px;
        padding-bottom: 25%;
    }
    
   
    .buttoncontainer {
        width: 100%;
        background-color: #62eb7e;
        text-align: center;
        padding-top: 125px;
        padding-bottom: 125px;
    }
    
    button {
        background-color: #62eb7e;
        border: 5px solid white;
        border-radius: 70px;
        font-family: "Roboto";
        font-size: 20px;
        padding: 15px 70px 15px 70px;
        box-shadow: 10px 10px 5px 58bb6b;
        transition: 1s
    }
    
    button:hover {
        background-color: white;
        border: 5px solid black;
    }
    
    @media (max-width: 400px) {
        .footerContainer {
            width: 400%
        }
    }
    
    @media(min-width: 900px) {
        .footerContainer {
            width: 200%
        }
    }
    
    .footerContainer {
        width: 100%;
        display: grid;
        grid-template-columns: 33% 33% 33%;
        padding-top: 10px;
        height: 350px;
        background-color: darkslategray;
    }
    
    .contentFooter p {
        padding-left: 20px;
        font-family: "Roboto";
        font-size: 12px;
        color: #62eb7e;
    }
    
    .contentFooter img {
        padding-left: 20px;
        width: 8%;
        height: 10%;
    }
    
    .column2 p {
        font-family: "Roboto";
        font-size: 14px;
        color: #62eb7e;
    }
    
    .column3 img {
        padding-top: 100px;
        padding-left: 20px;
        width: 25%;
        height: 20%;
    }
    </style>
</head>
<body>
    <div class="navigation">
        <a href="{% url 'Scheduler:index'%}">Home</a>
        
        {% if user.id == 1 %}
        <a href="{% url 'Scheduler:students' %}">Student List</a>
        {% endif %}

        {% if user.is_authenticated%}
        <a href="{% url 'Scheduler:student' user.pk%}"> View Schedule</a>
        {% else %}
            <a href="{% url 'Scheduler:login'%}">View Schedule</a>
        {% endif %}

        {% if user.is_authenticated %}
            <a href= "{% url 'Scheduler:logout'%}">Logout</a>
        {% else %}
            <a href="{% url 'Scheduler:login'%}">Login</a>
        {% endif %}  
    </div>

    <div class="grid1">
        <h1>
            <b>Welcome To <br>
              CourseTrader <br>
              <br></b>
        </h1>
        <img src="images/user_interface_monochromatic.png" alt="Woman and Car">

    </div>


    <div class="grid">
        <h1>
            Connect with your peers. <br> Take charge of your future.<br><br>
        </h1>
        <p>
            CourseTrader allows you to trade classes with your peers
        </p>
    </div>

    <div class="grid2">
        <h1>
            Never settle again. <br> Education should be tailored to you.<br><br>
        </h1>
        <p>
            Store your schedule data and preferences and our algorithm will pair you with a student with the classes you want
        </p>
        
    </div>


        <div class=buttoncontainer>
            <a href="{% url 'Scheduler:register'%}"><button type="button"> <h1><b> Click to register and begin trading</b> </h1></button></a>

        </div>


        <br>
        <div class=footerContainer>
            <div class="contentFooter">
                <p>+3302412811 <br> muraribhimavarapu@gmail.com</p>
                <br>
                <p>14894 Emberdale Dr, <br> Gainesville, FL, 32608, US</p>

                <br>
                <img src="images/Websiteicons-05.png" alt="linkedIn">
                <img src="images/Websiteicons-06.png" alt="facebook">
                <img src="images/Websiteicons-07.png" alt="instagram">

            </div>

            <div class="column2">
                <p>Student Made | Student Owned  <br><br><br> Privacy Policy <br><br> Terms of Services <br><br> Terms of Use
                    <br><br> Capability Statement</p>
            </div>

            <div class="column3">
                <img src="images/SWaM_LOGO.jpg" alt="swam">
                <img src="images/SWaM_LOGO.jpg" alt="swam">
                <img src="images/SWaM_LOGO.jpg" alt="swam">
            </div>
        </div>

</body>
</html>

GitHubCode/CourseTrader Web Application/Scheduler/templates/Scheduler/login.html
<!DOCTYPE html>
<head>
<style>
    .navigation {
        overflow: hidden;
        font-family: 'Roboto', sans-serif;
    }
    
    .navigation a {
        float: left;
        color: black;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 14px;
    }
    
    .navigation a:hover {
        background-color: rgb(98, 236, 125);
        color: black;
    }
</style>
</head>
<header>

</header>
<body>

<div class="navigation">
        <a href="{% url 'Scheduler:index'%}">Home</a>
        
        {% if user.id == 1 %}
        <a href="{% url 'Scheduler:students' %}">Student List</a>
        {% endif %}

        {% if user.is_authenticated%}
        <a href="{% url 'Scheduler:student' user.pk%}"> View Schedule</a>
        {% else %}
            <a href="{% url 'Scheduler:login'%}">View Schedule</a>
        {% endif %}

        {% if user.is_authenticated %}
            <a href= "{% url 'Scheduler:logout'%}">Logout</a>
        {% else %}
            <a href="{% url 'Scheduler:login'%}">Login</a>
        {% endif %}  
    </div>

<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form}}  
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  <p class="text-center">Don't have an account? <a href="{% url 'Scheduler:register'%}">Create an account</a>.</p>
</div>

</body>
</html>

GitHubCode/CourseTrader Web Application/Scheduler/templates/Scheduler/pairing.html
<!DOCTYPE html>
<head>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@900&display=swap" rel="stylesheet">
<style>
    .navigation {
        overflow: hidden;
        font-family: 'Roboto', sans-serif;
    }
    
    .navigation a {
        float: left;
        color: black;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 14px;
    }
    
    .navigation a:hover {
        background-color: rgb(98, 236, 125);
        color: black;
    }

    .row {
        display: flex;
        height: 100vh;
    }

    .column {
        flex: 50%;
        padding-left: 2%;
        border: 5px solid black;
    }

    .row {
        background-color: rgb(98, 236, 125);
    }

    h1 {
        font-family: 'Roboto', sans-serif;
    }

    p{
        font-family: 'Roboto';
    }
</style>
</head>
<header>

</header>
<body>
<div class="navigation">
        <a href="{% url 'Scheduler:index'%}">Home</a>
        
        {% if user.id == 1 %}
        <a href="{% url 'Scheduler:students' %}">Student List</a>
        {% endif %}

        {% if user.is_authenticated%}
        <a href="{% url 'Scheduler:student' user.pk%}"> View Schedule</a>
        {% else %}
            <a href="{% url 'Scheduler:login'%}">View Schedule</a>
        {% endif %}

        {% if user.is_authenticated %}
            <a href= "{% url 'Scheduler:logout'%}">Logout</a>
        {% else %}
            <a href="{% url 'Scheduler:login'%}">Login</a>
        {% endif %}  
    </div>

<h1> PAIRINGS </h1>
{% if pairing %}
    {% for pair in pairing %}
    <!-- printing course names -->
    <li><p> <b>{{pair.0.lastname}}, {{pair.0.firstname}} </b><br>
            Course: {{pair.1.course_number}}: {{pair.1.course_name}} <br>
            Period: {{pair.2}}
            </p>
    </li>
    {% endfor %}
  </ul>
  {% else %}
  <p>No pairings are available.</p>
  {% endif %}
  


     


</body>    

GitHubCode/CourseTrader Web Application/Scheduler/templates/Scheduler/register.html
<!DOCTYPE html>
<head>
<style>
    .navigation {
        overflow: hidden;
        font-family: 'Roboto', sans-serif;
    }
    
    .navigation a {
        float: left;
        color: black;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 14px;
    }
    
    .navigation a:hover {
        background-color: rgb(98, 236, 125);
        color: black;
    }
</style>
</head>
<header>
</header>
<body>
<div class="navigation">
        <a href="{% url 'Scheduler:index'%}">Home</a>
        
        {% if user.id == 1 %}
        <a href="{% url 'Scheduler:students' %}">Student List</a>
        {% endif %}

        {% if user.is_authenticated%}
        <a href="{% url 'Scheduler:student' user.pk%}"> View Schedule</a>
        {% else %}
            <a href="{% url 'Scheduler:login'%}">View Schedule</a>
        {% endif %}

        {% if user.is_authenticated %}
            <a href= "{% url 'Scheduler:logout'%}">Logout</a>
        {% else %}
            <a href="{% url 'Scheduler:login'%}">Login</a>
        {% endif %}  
    </div>



<!--Register--> 
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
        {% csrf_token %}
        {{ student_form}} 
        <br></br>
        {% csrf_token %}
		{{ register_form}} 
                  
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="{% url 'Scheduler:login'%}">login</a> instead.</p>
</div>


<body>

GitHubCode/CourseTrader Web Application/Scheduler/templates/Scheduler/student.html
<!DOCTYPE html>
<head>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@900&display=swap" rel="stylesheet">
<style>
    .navigation {
        overflow: hidden;
        font-family: 'Roboto', sans-serif;
    }
    
    .navigation a {
        float: left;
        color: black;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 14px;
    }
    
    .navigation a:hover {
        background-color: rgb(98, 236, 125);
        color: black;
    }

    .row {
        display: flex;
        height: 100vh;
    }

    .column {
        flex: 50%;
        padding-left: 2%;
        border: 5px solid black;
    }

    .row {
        background-color: rgb(98, 236, 125);
    }

    h1 {
        font-family: 'Roboto', sans-serif;
    }

    p{
        font-family: 'Roboto';
    }
</style>
</head>
<header>

</header>
<body>
<div class="navigation">
        <a href="{% url 'Scheduler:index'%}">Home</a>
        
        {% if user.id == 1 %}
        <a href="{% url 'Scheduler:students' %}">Student List</a>
        {% endif %}

        {% if user.is_authenticated%}
        <a href="{% url 'Scheduler:student' user.pk%}"> View Schedule</a>
        {% else %}
            <a href="{% url 'Scheduler:login'%}">View Schedule</a>
        {% endif %}

        {% if user.is_authenticated %}
            <a href= "{% url 'Scheduler:logout'%}">Logout</a>
        {% else %}
            <a href="{% url 'Scheduler:login'%}">Login</a>
        {% endif %}  
    </div>

<div class="row">
  <div class="column">
  <h1>ENROLLED COURSES </h1>
    {% if course_list %}
  <ul>
    {% for course in course_list %}
    <!-- printing course names -->
    <li><p> <b>{{course.0.course_number}}: {{course.0.course_name}}</b>  <br>
            Period: {{course.1}}
    </p></li>
    {% endfor %}
  </ul>
  {% else %}
  <p>No courses are available.</p>
  {% endif %}
  <a href="{% url 'Scheduler:addclass' user.pk%}"><button type="button"> <h1><b> Add a New Class to Schedule</b> </h1></button></a>

  </div>

  <div class="column"><h1>WISHLIST COURSES </h1>
  <ul>
    {% if courses %}
    {% for course in courses %}
    <!-- printing course names -->
    <li><p> <b>{{course.0.course_number}}: {{course.0.course_name}}</b>  <br>
            Period: {{course.1}}
    </p></li>
    {% endfor %}
  </ul>
  {% else %}
  <p>No courses are available.</p>
  {% endif %}
  <a href="{% url 'Scheduler:addwish' user.pk%}"><button type="button"> <h1><b> Add a New Class to Wishlist</b> </h1></button></a>


  </div>
     


</body>    

GitHubCode/CourseTrader Web Application/Scheduler/templates/Scheduler/students.html
<!DOCTYPE html>
<head>
<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@900&display=swap" rel="stylesheet">

<style>
    .navigation {
        overflow: hidden;
        font-family: 'Roboto', sans-serif;
    }
    
    .navigation a {
        float: left;
        color: black;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 14px;
    }
    
    .navigation a:hover {
        background-color: rgb(98, 236, 125);
        color: black;


    li {
       font-family: 'Roboto', sans-serif;
    }

</style>
</head>
<header>

</header>
<body>
<div class="navigation">
        <a href="{% url 'Scheduler:index'%}">Home</a>
        
        {% if user.id == 1 %}
        <a href="{% url 'Scheduler:students' %}">Student List</a>
        {% endif %}

        {% if user.is_authenticated%}
        <a href="{% url 'Scheduler:student' user.pk%}"> View Schedule</a>
        {% else %}
            <a href="{% url 'Scheduler:login'%}">View Schedule</a>
        {% endif %}

        {% if user.is_authenticated %}
            <a href= "{% url 'Scheduler:logout'%}">Logout</a>
        {% else %}
            <a href="{% url 'Scheduler:login'%}">Login</a>
        {% endif %}  
    </div>>
    {% if student_list %}
  <ul class>
    {% for student in student_list %}
    <!-- using namespaced URL names -->
    <li><a href="{% url 'Scheduler:student' student.pk %}">{{ student.lastname }}, {{student.firstname}}</a></li>
    {% endfor %}
  </ul>
  {% else %}
  <p>No students are available.</p>
  {% endif %} 
</body>    